// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlKsdX8-W7zXwA61Fpap7UP5ZMmNci_k',
    appId: '1:652922747833:web:1498afd1b82d2af6001468',
    messagingSenderId: '652922747833',
    projectId: 'smarthotpotmanager',
    authDomain: 'smarthotpotmanager.firebaseapp.com',
    storageBucket: 'smarthotpotmanager.firebasestorage.app',
    measurementId: 'G-HNWBHQ5TL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUJvdZimM280CxGj9_gcSDC8ssL29jJk',
    appId: '1:652922747833:android:2d14d014544a3a25001468',
    messagingSenderId: '652922747833',
    projectId: 'smarthotpotmanager',
    storageBucket: 'smarthotpotmanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKhE3yem7Fd2hEzAUvhajX-FllTZ4d3wc',
    appId: '1:652922747833:ios:048d62d68cfe8acc001468',
    messagingSenderId: '652922747833',
    projectId: 'smarthotpotmanager',
    storageBucket: 'smarthotpotmanager.firebasestorage.app',
    iosBundleId: 'com.example.smartHotpotManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKhE3yem7Fd2hEzAUvhajX-FllTZ4d3wc',
    appId: '1:652922747833:ios:048d62d68cfe8acc001468',
    messagingSenderId: '652922747833',
    projectId: 'smarthotpotmanager',
    storageBucket: 'smarthotpotmanager.firebasestorage.app',
    iosBundleId: 'com.example.smartHotpotManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKlKsdX8-W7zXwA61Fpap7UP5ZMmNci_k',
    appId: '1:652922747833:web:0c393c56203b6a71001468',
    messagingSenderId: '652922747833',
    projectId: 'smarthotpotmanager',
    authDomain: 'smarthotpotmanager.firebaseapp.com',
    storageBucket: 'smarthotpotmanager.firebasestorage.app',
    measurementId: 'G-WQ2GM7BNZW',
  );
}
